# Generated by Django 5.2.10 on 2026-01-12 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPTGroupMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpt_code", models.CharField(max_length=10)),
                ("cpt_group", models.CharField(max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpt_group_mappings",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "cpt_code")},
            },
        ),
        migrations.CreateModel(
            name="PayerMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payer_mappings",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "raw_name")},
            },
        ),
    ]
