# Generated by Django 5.2.10 on 2026-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0005_remove_reportartifact_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="routing_channels",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific channels to route this alert to. If empty, uses all enabled channels.",
                related_name="alert_rules",
                to="upstream.notificationchannel",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="routing_priority",
            field=models.IntegerField(
                default=0,
                help_text="Priority for rule evaluation order (higher = earlier)",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="routing_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for categorizing and routing alerts",
            ),
        ),
    ]
