# Generated by Django 5.2.10 on 2026-01-19 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0008_alter_domainauditevent_action_ingestionrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_slug",
                    models.CharField(
                        choices=[
                            ("upstream-core", "Upstream Core"),
                            ("denialscope", "DenialScope"),
                            ("contractiq", "ContractIQ"),
                            ("opsvariance", "OpsVariance"),
                            ("authsignal", "AuthSignal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "config_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Product-specific configuration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_configs",
                        to="upstream.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Configuration",
                "verbose_name_plural": "Product Configurations",
                "ordering": ["customer", "product_slug"],
                "unique_together": {("customer", "product_slug")},
            },
        ),
    ]
