# Generated by Django 5.2.10 on 2026-01-19 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0010_claimrecord_denial_reason_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DenialAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payer", models.CharField(db_index=True, max_length=255)),
                (
                    "denial_reason",
                    models.CharField(
                        blank=True,
                        help_text='Denial reason code or generic "DENIED"',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cpt_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional CPT code filter",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "aggregate_date",
                    models.DateField(db_index=True, help_text="Day of aggregation"),
                ),
                ("denied_count", models.IntegerField(default=0)),
                (
                    "denied_dollars",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of allowed_amount for denials",
                        max_digits=12,
                    ),
                ),
                (
                    "total_submitted_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total claims submitted to this payer on this day",
                    ),
                ),
                (
                    "total_submitted_dollars",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "denial_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denial_aggregates",
                        to="upstream.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Denial Aggregate",
                "verbose_name_plural": "Denial Aggregates",
                "ordering": ["-aggregate_date", "-denied_count"],
            },
        ),
        migrations.CreateModel(
            name="DenialSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("new_denial_reason", "New Denial Reason"),
                            ("denial_rate_spike", "Denial Rate Spike"),
                            ("denial_volume_spike", "Denial Volume Spike"),
                            ("denial_dollars_spike", "Denial Dollars Spike"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("payer", models.CharField(db_index=True, max_length=255)),
                (
                    "denial_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("window_start_date", models.DateField()),
                ("window_end_date", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score 0-1",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Human-readable signal summary"),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Signal-specific metrics and context"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denial_signals",
                        to="upstream.customer",
                    ),
                ),
                (
                    "related_aggregates",
                    models.ManyToManyField(
                        blank=True, related_name="signals", to="upstream.denialaggregate"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Denial Signal",
                "verbose_name_plural": "Denial Signals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="denialaggregate",
            index=models.Index(
                fields=["customer", "aggregate_date"],
                name="upstream_den_custome_b5ec09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialaggregate",
            index=models.Index(
                fields=["customer", "payer", "aggregate_date"],
                name="upstream_den_custome_2006d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialaggregate",
            index=models.Index(
                fields=["customer", "payer", "denial_reason", "aggregate_date"],
                name="upstream_den_custome_1b794c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="denialaggregate",
            constraint=models.UniqueConstraint(
                fields=(
                    "customer",
                    "payer",
                    "denial_reason",
                    "cpt_code",
                    "aggregate_date",
                ),
                name="unique_denial_aggregate",
            ),
        ),
        migrations.AddIndex(
            model_name="denialsignal",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="upstream_den_custome_035c37_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialsignal",
            index=models.Index(
                fields=["customer", "signal_type", "-created_at"],
                name="upstream_den_custome_473e97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialsignal",
            index=models.Index(
                fields=["customer", "severity", "-created_at"],
                name="upstream_den_custome_4ef3de_idx",
            ),
        ),
    ]
