# Generated by Django 5.2.10 on 2026-01-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0011_denialaggregate_denialsignal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ingestion_received", "Ingestion Received"),
                    ("ingestion_processed", "Ingestion Processed"),
                    ("ingestion_failed", "Ingestion Failed"),
                    ("drift_detected", "Drift Detected"),
                    ("alert_created", "Alert Created"),
                    ("export_generated", "Export Generated"),
                    ("report_generated", "Report Generated"),
                    ("webhook_sent", "Webhook Sent"),
                    ("email_sent", "Email Sent"),
                    ("denialscope_signal_created", "DenialScope Signal Created"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
