# Generated by Django 5.2.10 on 2026-01-22 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0012_alter_systemevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorJudgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("noise", "Noise"),
                            ("real", "Real/Legitimate"),
                            ("needs_followup", "Needs Follow-up"),
                        ],
                        help_text="Operator verdict on the alert",
                        max_length=20,
                    ),
                ),
                (
                    "reason_codes_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of reason codes or tags explaining the judgment",
                    ),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dollar amount recovered from this alert (if applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "recovered_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when recovery was confirmed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional operator notes"),
                ),
                (
                    "alert_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_judgments",
                        to="upstream.alertevent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_judgments",
                        to="upstream.customer",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        help_text="Operator who made the judgment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_judgments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator Judgment",
                "verbose_name_plural": "Operator Judgments",
                "ordering": ["-created_at"],
                "unique_together": {("alert_event", "operator")},
            },
        ),
    ]
