# Generated by Django 5.2.10 on 2026-01-24 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0013_operatorjudgment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["customer", "status", "-triggered_at"],
                name="alertevt_cust_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["customer", "-notification_sent_at"],
                name="alertevt_cust_sent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["alert_rule", "-triggered_at"], name="alertevt_rule_trig_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "submitted_date"], name="claim_cust_subdate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "decided_date"], name="claim_cust_decdate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "payer", "submitted_date"],
                name="claim_cust_payer_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "outcome", "decided_date"],
                name="claim_cust_outcome_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "-created_at"], name="drift_cust_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "payer", "drift_type"],
                name="drift_cust_payer_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "drift_type", "-created_at"],
                name="drift_cust_type_date_idx",
            ),
        ),
    ]
