# Generated by Django 5.2.10 on 2026-01-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0014_alertevent_alertevt_cust_status_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQualityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(default=0, help_text="Total rows in CSV file"),
                ),
                (
                    "accepted_rows",
                    models.IntegerField(
                        default=0, help_text="Rows that passed validation"
                    ),
                ),
                (
                    "rejected_rows",
                    models.IntegerField(
                        default=0, help_text="Rows that failed validation"
                    ),
                ),
                (
                    "rejection_details",
                    models.JSONField(
                        default=dict,
                        help_text="Map of row numbers to rejection reasons: {row_num: reason}",
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        default=list,
                        help_text="List of warning messages: [{row: int, message: str}]",
                    ),
                ),
                (
                    "phi_detections",
                    models.IntegerField(
                        default=0, help_text="Number of rows rejected for potential PHI"
                    ),
                ),
                (
                    "missing_fields",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rows rejected for missing required fields",
                    ),
                ),
                (
                    "invalid_dates",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rows rejected for invalid date formats",
                    ),
                ),
                (
                    "invalid_values",
                    models.IntegerField(
                        default=0,
                        help_text="Number of rows rejected for invalid field values",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_reports",
                        to="upstream.customer",
                    ),
                ),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_report",
                        to="upstream.upload",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"], name="dqr_cust_created_idx"
                    ),
                    models.Index(fields=["upload"], name="dqr_upload_idx"),
                ],
            },
        ),
    ]
