# Generated by Django 5.2.10 on 2026-01-16 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0004_systemconfiguration_alertrule_alertevent_alert_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportartifact",
            name="format",
        ),
        migrations.RemoveField(
            model_name="reportartifact",
            name="params",
        ),
        migrations.RemoveField(
            model_name="reportartifact",
            name="status",
        ),
        migrations.AddField(
            model_name="reportartifact",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA256 hash of file content for idempotency",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="reportartifact",
            name="kind",
            field=models.CharField(
                default="weekly_drift_summary",
                help_text="Type of report artifact (e.g., weekly_drift_summary)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reportartifact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When the artifact was generated"
            ),
        ),
        migrations.AlterField(
            model_name="reportartifact",
            name="file_path",
            field=models.CharField(
                blank=True, help_text="Path to the generated PDF file", max_length=512
            ),
        ),
        migrations.AddConstraint(
            model_name="reportartifact",
            constraint=models.UniqueConstraint(
                fields=("customer", "report_run", "kind"),
                name="unique_artifact_per_customer_report_kind",
            ),
        ),
    ]
