# Generated by Django 5.2.10 on 2026-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0006_add_alert_routing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("analyst", "Analyst"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=20,
            ),
        ),
    ]
