# Generated by Django 5.2.10 on 2026-01-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0007_add_role_to_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("upload_created", "Upload Created"),
                    ("report_exported", "Report Exported"),
                    ("alert_rule_created", "Alert Rule Created"),
                    ("alert_rule_updated", "Alert Rule Updated"),
                    ("alert_rule_deleted", "Alert Rule Deleted"),
                    ("alert_event_created", "Alert Event Created"),
                    ("alert_event_sent", "Alert Event Sent"),
                    ("alert_event_failed", "Alert Event Failed"),
                    ("webhook_delivery_attempted", "Webhook Delivery Attempted"),
                    ("webhook_delivery_sent", "Webhook Delivery Sent"),
                    ("webhook_delivery_failed", "Webhook Delivery Failed"),
                    ("webhook_endpoint_created", "Webhook Endpoint Created"),
                    ("webhook_endpoint_updated", "Webhook Endpoint Updated"),
                    ("webhook_endpoint_deleted", "Webhook Endpoint Deleted"),
                    ("drift_event_created", "Drift Event Created"),
                    ("report_run_started", "Report Run Started"),
                    ("report_run_completed", "Report Run Completed"),
                    ("member_added", "Member Added"),
                    ("member_removed", "Member Removed"),
                    ("role_changed", "Role Changed"),
                    ("alert_routing_updated", "Alert Routing Updated"),
                    ("slack_webhook_updated", "Slack Webhook Updated"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="IngestionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("batch_upload", "Batch Upload"),
                            ("webhook", "Webhook"),
                            ("api", "API"),
                            ("streaming", "Streaming"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique key to prevent duplicate processing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payload_metadata",
                    models.JSONField(
                        default=dict, help_text="Metadata about the ingested payload"
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(
                        blank=True, help_text="Number of records in payload", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_records",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Record",
                "verbose_name_plural": "Ingestion Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this token", max_length=100
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_tokens",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Token",
                "verbose_name_plural": "Ingestion Tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ingestion_received", "Ingestion Received"),
                            ("ingestion_processed", "Ingestion Processed"),
                            ("ingestion_failed", "Ingestion Failed"),
                            ("drift_detected", "Drift Detected"),
                            ("alert_created", "Alert Created"),
                            ("export_generated", "Export Generated"),
                            ("report_generated", "Report Generated"),
                            ("webhook_sent", "Webhook Sent"),
                            ("email_sent", "Email Sent"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Event-specific data"),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_events",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "related_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_events",
                        to="payrixa.alertevent",
                    ),
                ),
                (
                    "related_drift_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_events",
                        to="payrixa.driftevent",
                    ),
                ),
                (
                    "related_ingestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="payrixa.ingestionrecord",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Event",
                "verbose_name_plural": "System Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestionrecord",
            index=models.Index(
                fields=["customer", "status", "-created_at"],
                name="payrixa_ing_custome_652af2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionrecord",
            index=models.Index(
                fields=["customer", "source_type", "-created_at"],
                name="payrixa_ing_custome_59f4cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("customer", "idempotency_key"),
                name="unique_customer_idempotency_key",
            ),
        ),
        migrations.AddIndex(
            model_name="systemevent",
            index=models.Index(
                fields=["customer", "event_type", "-created_at"],
                name="payrixa_sys_custome_5f7c4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemevent",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="payrixa_sys_custome_854bdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="payrixa_sys_event_t_abc3b2_idx",
            ),
        ),
    ]
