# Generated by Django 5.2.10 on 2026-01-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0009_productconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimrecord",
            name="denial_reason_code",
            field=models.CharField(
                blank=True,
                help_text="Denial reason code from payer",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="denial_reason_text",
            field=models.TextField(
                blank=True, help_text="Denial reason description", null=True
            ),
        ),
    ]
