# Generated by Django 5.2.10 on 2026-01-24 06:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0015_dataqualityreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appeal_id", models.CharField(db_index=True, max_length=50)),
                (
                    "appeal_letter",
                    models.TextField(help_text="Generated appeal letter content"),
                ),
                (
                    "required_documentation",
                    models.JSONField(
                        default=list, help_text="List of required supporting documents"
                    ),
                ),
                ("denial_reason", models.CharField(max_length=255)),
                (
                    "appeal_reason",
                    models.TextField(help_text="Reason/argument for appeal"),
                ),
                (
                    "supporting_evidence",
                    models.JSONField(
                        default=list, help_text="List of supporting evidence points"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready to Submit"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Appeal Approved"),
                            ("partial", "Partially Approved"),
                            ("denied", "Appeal Denied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recovered_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount recovered from successful appeal",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "generation_confidence",
                    models.FloatField(
                        default=0.8,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("ai_model_version", models.CharField(default="gpt-4", max_length=50)),
                (
                    "edited_by_user",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user manually edited the generated appeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal Generation",
                "verbose_name_plural": "Appeal Generations",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AppealTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template_id", models.CharField(db_index=True, max_length=50)),
                ("template_name", models.CharField(max_length=200)),
                ("denial_reason_code", models.CharField(blank=True, max_length=50)),
                (
                    "denial_reason_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for denial reason text matching",
                        max_length=255,
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        blank=True,
                        help_text="Specific payer (if template is payer-specific)",
                        max_length=255,
                    ),
                ),
                (
                    "cpt_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="CPT codes this template applies to",
                    ),
                ),
                (
                    "appeal_letter_template",
                    models.TextField(
                        help_text="Appeal letter template with {variable} placeholders"
                    ),
                ),
                (
                    "required_documentation",
                    models.JSONField(
                        default=list, help_text="List of required supporting documents"
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                (
                    "success_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of successful appeals using this template",
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Success rate (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("generated_by_ai", models.BooleanField(default=True)),
                (
                    "generation_confidence",
                    models.FloatField(
                        default=0.8,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("ai_model_version", models.CharField(default="gpt-4", max_length=50)),
                ("active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Appeal Template",
                "verbose_name_plural": "Appeal Templates",
                "ordering": ["-success_rate", "-times_used"],
            },
        ),
        migrations.CreateModel(
            name="ClaimValidationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validation_passed", models.BooleanField(db_index=True, default=True)),
                ("error_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall quality score for this claim",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        default=list,
                        help_text="List of validation errors: [{rule_code, message, field}]",
                    ),
                ),
                (
                    "validation_warnings",
                    models.JSONField(
                        default=list, help_text="List of validation warnings"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Claim Validation History",
                "verbose_name_plural": "Claim Validation Histories",
                "ordering": ["-validated_at"],
            },
        ),
        migrations.CreateModel(
            name="DataAnomalyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("statistical_outlier", "Statistical Outlier"),
                            ("pattern_break", "Pattern Break"),
                            ("volume_anomaly", "Volume Anomaly"),
                            ("distribution_shift", "Distribution Shift"),
                            ("missing_data_spike", "Missing Data Spike"),
                            ("duplicate_spike", "Duplicate Spike"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(
                        help_text="Anomaly score (higher = more anomalous)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence in anomaly detection",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Human-readable anomaly description"),
                ),
                (
                    "statistical_details",
                    models.JSONField(
                        default=dict,
                        help_text="Statistical details: mean, std, z-score, etc.",
                    ),
                ),
                ("affected_row_count", models.IntegerField(default=0)),
                (
                    "recommended_action",
                    models.TextField(
                        blank=True, help_text="Recommended remediation action"
                    ),
                ),
                ("acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Data Anomaly Detection",
                "verbose_name_plural": "Data Anomaly Detections",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("completeness", "Completeness"),
                            ("accuracy", "Accuracy"),
                            ("consistency", "Consistency"),
                            ("timeliness", "Timeliness"),
                            ("validity", "Validity"),
                            ("uniqueness", "Uniqueness"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(help_text="Specific metric name", max_length=100),
                ),
                ("measurement_date", models.DateField(db_index=True)),
                (
                    "measurement_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Quality score from 0.0 (worst) to 1.0 (perfect)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(help_text="Number of records measured"),
                ),
                (
                    "passed_count",
                    models.IntegerField(
                        help_text="Number of records passing quality check"
                    ),
                ),
                (
                    "failed_count",
                    models.IntegerField(
                        help_text="Number of records failing quality check"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        default="claim_record",
                        help_text="Type of entity measured (claim_record, upload, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        help_text="Optional dimension (payer, cpt_group, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "dimension_value",
                    models.CharField(
                        blank=True,
                        help_text="Value of the dimension (if applicable)",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed breakdown and supporting metrics",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Quality Metric",
                "verbose_name_plural": "Data Quality Metrics",
                "ordering": ["-measurement_date", "-measurement_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DenialCascade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cascade_id", models.CharField(db_index=True, max_length=50)),
                (
                    "cascade_type",
                    models.CharField(
                        choices=[
                            ("temporal", "Temporal - Same timeframe"),
                            ("procedural", "Procedural - Related procedures"),
                            ("payer_systemic", "Payer Systemic - Payer-wide issue"),
                            ("documentation", "Documentation - Same doc issue"),
                        ],
                        default="temporal",
                        max_length=50,
                    ),
                ),
                (
                    "claim_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of ClaimRecord IDs in this cascade",
                    ),
                ),
                ("claim_count", models.IntegerField(default=0)),
                ("payer", models.CharField(max_length=255)),
                ("denial_reasons", models.JSONField(default=list)),
                (
                    "total_denied_dollars",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "pattern_summary",
                    models.TextField(help_text="Description of the cascade pattern"),
                ),
                (
                    "root_cause",
                    models.TextField(
                        blank=True, help_text="Identified or suspected root cause"
                    ),
                ),
                (
                    "resolution_recommended",
                    models.TextField(
                        blank=True, help_text="Recommended resolution strategy"
                    ),
                ),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("cascade_start_date", models.DateField()),
                ("cascade_end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Denial Cascade",
                "verbose_name_plural": "Denial Cascades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DenialCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique cluster identifier (e.g., CLU-2024-001)",
                        max_length=50,
                    ),
                ),
                (
                    "cluster_name",
                    models.CharField(
                        help_text="Human-readable cluster name", max_length=200
                    ),
                ),
                ("primary_denial_reason", models.CharField(max_length=255)),
                (
                    "secondary_denial_reasons",
                    models.JSONField(
                        default=list, help_text="Other denial reasons in this cluster"
                    ),
                ),
                (
                    "payers",
                    models.JSONField(
                        default=list, help_text="List of payers in this cluster"
                    ),
                ),
                (
                    "cpt_codes",
                    models.JSONField(
                        default=list, help_text="List of CPT codes in this cluster"
                    ),
                ),
                ("claim_count", models.IntegerField(default=0)),
                (
                    "total_denied_dollars",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cluster_confidence",
                    models.FloatField(
                        help_text="Confidence score for cluster cohesion (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "silhouette_score",
                    models.FloatField(
                        blank=True,
                        help_text="ML silhouette score for cluster quality",
                        null=True,
                    ),
                ),
                (
                    "pattern_description",
                    models.TextField(
                        help_text="AI-generated description of the denial pattern"
                    ),
                ),
                (
                    "root_cause_hypothesis",
                    models.TextField(
                        help_text="AI-generated hypothesis about root cause"
                    ),
                ),
                (
                    "resolution_strategy",
                    models.TextField(
                        blank=True,
                        help_text="Recommended resolution strategy for this cluster",
                    ),
                ),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("first_denial_date", models.DateField()),
                ("last_denial_date", models.DateField()),
            ],
            options={
                "verbose_name": "Denial Cluster",
                "verbose_name_plural": "Denial Clusters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreDenialWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("warning_id", models.CharField(db_index=True, max_length=50)),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("auth_missing", "Authorization Missing"),
                            ("doc_incomplete", "Documentation Incomplete"),
                            ("coding_error", "Coding Error Likely"),
                            ("policy_violation", "Policy Violation Risk"),
                            ("payer_pattern", "Payer Pattern Match"),
                        ],
                        max_length=50,
                    ),
                ),
                ("predicted_denial_reason", models.CharField(max_length=255)),
                (
                    "denial_probability",
                    models.FloatField(
                        help_text="Predicted probability of denial (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Model confidence in prediction",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        default=list,
                        help_text="List of identified risk factors: [{factor, weight}]",
                    ),
                ),
                ("payer", models.CharField(max_length=255)),
                ("cpt_code", models.CharField(blank=True, max_length=50)),
                (
                    "estimated_claim_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        default=list,
                        help_text="Recommended actions to prevent denial: [{action, priority}]",
                    ),
                ),
                (
                    "intervention_deadline",
                    models.DateField(
                        blank=True, help_text="Deadline for intervention", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("intervened", "Intervention Taken"),
                            ("expired", "Expired"),
                            ("confirmed", "Denial Confirmed"),
                            ("avoided", "Denial Avoided"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "actual_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paid", "Paid"),
                            ("denied", "Denied"),
                            ("pending", "Pending"),
                        ],
                        help_text="Actual claim outcome (for model feedback)",
                        max_length=20,
                    ),
                ),
                (
                    "intervention_taken",
                    models.TextField(
                        blank=True, help_text="Description of intervention taken"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="v1.0",
                        help_text="ML model version used for prediction",
                        max_length=50,
                    ),
                ),
                (
                    "prediction_features",
                    models.JSONField(
                        default=dict,
                        help_text="Features used in prediction (for explainability)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Denial Warning",
                "verbose_name_plural": "Pre-Denial Warnings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "row_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Row number in CSV (if applicable)",
                        null=True,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                (
                    "field_value",
                    models.TextField(
                        blank=True, help_text="The value that failed validation"
                    ),
                ),
                ("passed", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error - Reject Row"),
                            ("warning", "Warning - Accept with Flag"),
                            ("info", "Info - Log Only"),
                        ],
                        db_index=True,
                        default="error",
                        max_length=20,
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the validation (full row data, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Result",
                "verbose_name_plural": "Validation Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable rule name", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Unique code for this rule (e.g., "REQ_001")',
                        max_length=50,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("required_field", "Required Field"),
                            ("format_check", "Format Check"),
                            ("range_check", "Range Check"),
                            ("date_logic", "Date Logic"),
                            ("phi_detection", "PHI Detection"),
                            ("reference_check", "Reference Data Check"),
                            ("business_rule", "Business Rule"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Field this rule applies to (if field-specific)",
                        max_length=100,
                    ),
                ),
                (
                    "validation_logic",
                    models.JSONField(
                        default=dict,
                        help_text="Rule-specific validation configuration (regex, min/max, etc.)",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error - Reject Row"),
                            ("warning", "Warning - Accept with Flag"),
                            ("info", "Info - Log Only"),
                        ],
                        default="error",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "error_message_template",
                    models.TextField(
                        help_text="Error message template with {field} placeholders"
                    ),
                ),
                (
                    "remediation_guidance",
                    models.TextField(
                        blank=True, help_text="How to fix violations of this rule"
                    ),
                ),
                (
                    "applies_to_entity",
                    models.CharField(
                        default="claim_record",
                        help_text="Entity type this rule applies to (claim_record, upload, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "execution_order",
                    models.IntegerField(
                        default=100,
                        help_text="Order in which rules are executed (lower = earlier)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Rule",
                "verbose_name_plural": "Validation Rules",
                "ordering": ["execution_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="authorization_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="authorization_obtained",
            field=models.BooleanField(
                default=False, help_text="Whether auth was obtained before service"
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="authorization_required",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether prior auth was required",
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="billed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original billed amount",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="data_quality_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of quality issues: [{severity, message, field}]",
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="data_quality_score",
            field=models.FloatField(
                blank=True,
                help_text="Quality score for this claim (0.0 = poor, 1.0 = perfect)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="diagnosis_codes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of diagnosis codes"
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="modifier_codes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of modifier codes used"
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount actually paid (may differ from allowed)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="payment_date",
            field=models.DateField(
                blank=True,
                help_text="Actual payment date (if different from decided_date)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="procedure_count",
            field=models.IntegerField(
                default=1, help_text="Number of procedures on this claim"
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="processed_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="source_data_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of source row for deduplication",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="source_row_number",
            field=models.IntegerField(
                blank=True, help_text="Row number in source CSV file", null=True
            ),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="validation_passed",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="claimrecord",
            name="validation_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="baseline_sample_size",
            field=models.IntegerField(
                default=0, help_text="Number of claims in baseline period"
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="baseline_std_dev",
            field=models.FloatField(
                blank=True, help_text="Standard deviation of baseline", null=True
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="consecutive_periods",
            field=models.IntegerField(
                default=1,
                help_text="Number of consecutive periods this drift has persisted",
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="current_sample_size",
            field=models.IntegerField(
                default=0, help_text="Number of claims in current period"
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="estimated_revenue_impact",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated monthly revenue impact of this drift",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="potential_root_causes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI-suggested root causes: [{cause, likelihood}]",
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="statistical_significance",
            field=models.FloatField(
                blank=True,
                help_text="P-value from statistical test (lower = more significant)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="suppressed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this event was suppressed from alerting",
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="suppression_reason",
            field=models.TextField(
                blank=True, help_text="Why this event was suppressed"
            ),
        ),
        migrations.AddField(
            model_name="driftevent",
            name="trend_direction",
            field=models.CharField(
                choices=[
                    ("improving", "Improving"),
                    ("degrading", "Degrading"),
                    ("stable", "Stable"),
                ],
                db_index=True,
                default="stable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="accepted_row_count",
            field=models.IntegerField(
                default=0, help_text="Number of rows that passed validation"
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="data_quality_issues",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Summary of data quality issues found",
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="file_encoding",
            field=models.CharField(
                blank=True, default="utf-8", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="file_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash for deduplication",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="file_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="processing_duration_seconds",
            field=models.IntegerField(
                blank=True, help_text="Time taken to process upload", null=True
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="rejected_row_count",
            field=models.IntegerField(
                default=0, help_text="Number of rows that failed validation"
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="upload_source",
            field=models.CharField(
                choices=[
                    ("web_ui", "Web UI"),
                    ("api", "API"),
                    ("batch", "Batch Process"),
                ],
                default="web_ui",
                help_text="How this file was uploaded",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded this file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="validation_errors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Summary of validation errors by type",
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="warning_row_count",
            field=models.IntegerField(
                default=0, help_text="Number of rows with warnings"
            ),
        ),
        migrations.AlterField(
            model_name="driftevent",
            name="drift_type",
            field=models.CharField(
                choices=[
                    ("DENIAL_RATE", "Denial Rate"),
                    ("DECISION_TIME", "Decision Time"),
                    ("PAYMENT_AMOUNT", "Payment Amount"),
                    ("APPROVAL_RATE", "Approval Rate"),
                    ("PROCESSING_DELAY", "Processing Delay"),
                    ("AUTH_FAILURE_RATE", "Authorization Failure Rate"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("partial", "Partial Success"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "authorization_required", "authorization_obtained"],
                name="claim_auth_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "validation_passed", "processed_at"],
                name="claim_validation_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "payment_date"], name="claim_payment_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "trend_direction", "-severity"],
                name="drift_trend_sev_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "suppressed", "-created_at"],
                name="drift_suppressed_idx",
            ),
        ),
        migrations.AddField(
            model_name="appealgeneration",
            name="claim_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appeals",
                to="payrixa.claimrecord",
            ),
        ),
        migrations.AddField(
            model_name="appealgeneration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appealgeneration",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appeal_generations",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="appealgeneration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appealtemplate",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_appeal_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appealtemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appealtemplate",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appeal_templates",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="appealtemplate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appealgeneration",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_appeals",
                to="payrixa.appealtemplate",
            ),
        ),
        migrations.AddField(
            model_name="claimvalidationhistory",
            name="claim_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validations",
                to="payrixa.claimrecord",
            ),
        ),
        migrations.AddField(
            model_name="claimvalidationhistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claimvalidationhistory",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_validations",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="claimvalidationhistory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claimvalidationhistory",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_validations",
                to="payrixa.upload",
            ),
        ),
        migrations.AddField(
            model_name="dataanomalydetection",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_anomalies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataanomalydetection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataanomalydetection",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_anomalies",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="dataanomalydetection",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataanomalydetection",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="payrixa.upload",
            ),
        ),
        migrations.AddField(
            model_name="dataqualitymetric",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataqualitymetric",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_metrics",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="dataqualitymetric",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="denialcascade",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="denialcascade",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="denial_cascades",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="denialcascade",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="denialcluster",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="denialcluster",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="denial_clusters",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="denialcluster",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_denial_clusters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="denialcluster",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="predenialwarning",
            name="claim_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific claim at risk (if available)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_denial_warnings",
                to="payrixa.claimrecord",
            ),
        ),
        migrations.AddField(
            model_name="predenialwarning",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="predenialwarning",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_denial_warnings",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="predenialwarning",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="claim_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_results",
                to="payrixa.claimrecord",
            ),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_results",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_results",
                to="payrixa.upload",
            ),
        ),
        migrations.AddField(
            model_name="validationrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validationrule",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_rules",
                to="payrixa.customer",
            ),
        ),
        migrations.AddField(
            model_name="validationrule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validationresult",
            name="validation_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_results",
                to="payrixa.validationrule",
            ),
        ),
        migrations.AddIndex(
            model_name="appealtemplate",
            index=models.Index(
                fields=["customer", "active", "-success_rate"],
                name="payrixa_app_custome_06a18a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appealtemplate",
            index=models.Index(
                fields=["customer", "denial_reason_code"],
                name="payrixa_app_custome_94d18f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appealtemplate",
            index=models.Index(
                fields=["customer", "payer"], name="payrixa_app_custome_fd69d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appealgeneration",
            index=models.Index(
                fields=["customer", "status", "-generated_at"],
                name="payrixa_app_custome_bff770_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appealgeneration",
            index=models.Index(
                fields=["customer", "claim_record"],
                name="payrixa_app_custome_038c41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appealgeneration",
            index=models.Index(
                fields=["customer", "outcome"], name="payrixa_app_custome_3237f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimvalidationhistory",
            index=models.Index(
                fields=["customer", "upload", "validation_passed"],
                name="payrixa_cla_custome_0df6da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimvalidationhistory",
            index=models.Index(
                fields=["customer", "claim_record", "-validated_at"],
                name="payrixa_cla_custome_744ede_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimvalidationhistory",
            index=models.Index(
                fields=["customer", "validation_passed", "-validated_at"],
                name="payrixa_cla_custome_a1a5a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataanomalydetection",
            index=models.Index(
                fields=["customer", "severity", "-detected_at"],
                name="payrixa_dat_custome_bb628a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataanomalydetection",
            index=models.Index(
                fields=["customer", "anomaly_type", "-detected_at"],
                name="payrixa_dat_custome_8b1a7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataanomalydetection",
            index=models.Index(
                fields=["customer", "acknowledged", "-detected_at"],
                name="payrixa_dat_custome_c06d64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitymetric",
            index=models.Index(
                fields=["customer", "metric_type", "-measurement_date"],
                name="payrixa_dat_custome_d4215d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitymetric",
            index=models.Index(
                fields=["customer", "measurement_date"],
                name="payrixa_dat_custome_d9e7dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataqualitymetric",
            index=models.Index(
                fields=["customer", "entity_type", "metric_type", "-measurement_date"],
                name="payrixa_dat_custome_c12fd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialcascade",
            index=models.Index(
                fields=["customer", "resolved", "-created_at"],
                name="payrixa_den_custome_8d1328_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialcascade",
            index=models.Index(
                fields=["customer", "payer", "cascade_type"],
                name="payrixa_den_custome_7eec71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialcluster",
            index=models.Index(
                fields=["customer", "resolved", "-created_at"],
                name="payrixa_den_custome_b399a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="denialcluster",
            index=models.Index(
                fields=["customer", "cluster_id"], name="payrixa_den_custome_13959b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="denialcluster",
            unique_together={("customer", "cluster_id")},
        ),
        migrations.AddIndex(
            model_name="predenialwarning",
            index=models.Index(
                fields=["customer", "status", "-created_at"],
                name="payrixa_pre_custome_646a38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="predenialwarning",
            index=models.Index(
                fields=["customer", "payer", "status"],
                name="payrixa_pre_custome_dba21b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="predenialwarning",
            index=models.Index(
                fields=["customer", "denial_probability"],
                name="payrixa_pre_custome_c31089_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrule",
            index=models.Index(
                fields=["customer", "enabled", "execution_order"],
                name="payrixa_val_custome_f562c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrule",
            index=models.Index(
                fields=["customer", "rule_type"], name="payrixa_val_custome_680ad6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="validationrule",
            unique_together={("customer", "code")},
        ),
        migrations.AddIndex(
            model_name="validationresult",
            index=models.Index(
                fields=["customer", "upload", "severity"],
                name="payrixa_val_custome_a7b0de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationresult",
            index=models.Index(
                fields=["customer", "validation_rule", "-created_at"],
                name="payrixa_val_custome_1ecf44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationresult",
            index=models.Index(
                fields=["customer", "passed", "-created_at"],
                name="payrixa_val_custome_755f57_idx",
            ),
        ),
    ]
