# Generated by Django 5.2.10 on 2026-01-24 07:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0016_appealgeneration_appealtemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDelayAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payer", models.CharField(db_index=True, max_length=255)),
                (
                    "aggregate_date",
                    models.DateField(db_index=True, help_text="Day of aggregation"),
                ),
                (
                    "claim_count",
                    models.IntegerField(
                        default=0, help_text="Total claims with valid dates"
                    ),
                ),
                (
                    "total_days_to_payment",
                    models.IntegerField(default=0, help_text="Sum of days to payment"),
                ),
                (
                    "avg_days_to_payment",
                    models.FloatField(default=0.0, help_text="Average days to payment"),
                ),
                (
                    "min_days_to_payment",
                    models.IntegerField(
                        blank=True, help_text="Minimum days to payment", null=True
                    ),
                ),
                (
                    "max_days_to_payment",
                    models.IntegerField(
                        blank=True, help_text="Maximum days to payment", null=True
                    ),
                ),
                (
                    "total_billed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of allowed_amount for included claims",
                        max_digits=14,
                    ),
                ),
                (
                    "total_rows_evaluated",
                    models.IntegerField(
                        default=0, help_text="Total rows including missing dates"
                    ),
                ),
                (
                    "rows_with_valid_dates",
                    models.IntegerField(
                        default=0,
                        help_text="Rows with both submitted and decided dates",
                    ),
                ),
                (
                    "date_completeness_ratio",
                    models.FloatField(
                        default=0.0,
                        help_text="Ratio of valid rows to total rows",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_delay_aggregates",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Delay Aggregate",
                "verbose_name_plural": "Payment Delay Aggregates",
                "ordering": ["-aggregate_date", "-claim_count"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDelayClaimSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payer", models.CharField(max_length=255)),
                ("window_start_date", models.DateField()),
                ("window_end_date", models.DateField()),
                (
                    "row_count",
                    models.IntegerField(help_text="Number of claims in this set"),
                ),
                (
                    "totals_json",
                    models.JSONField(
                        default=dict, help_text="Aggregate totals for the claim set"
                    ),
                ),
                (
                    "source_refs_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of claim IDs or surrogate keys",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 of sorted claim IDs",
                        max_length=255,
                    ),
                ),
                ("frozen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_delay_claimsets",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Delay Claim Set",
                "verbose_name_plural": "Payment Delay Claim Sets",
                "ordering": ["-frozen_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDelaySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[("payment_delay_drift", "Payment Delay Drift")],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("payer", models.CharField(db_index=True, max_length=255)),
                ("window_start_date", models.DateField()),
                ("window_end_date", models.DateField()),
                ("baseline_start_date", models.DateField()),
                ("baseline_end_date", models.DateField()),
                (
                    "baseline_avg_days",
                    models.FloatField(help_text="Baseline average days to payment"),
                ),
                (
                    "current_avg_days",
                    models.FloatField(
                        help_text="Current window average days to payment"
                    ),
                ),
                (
                    "delta_days",
                    models.FloatField(help_text="Change in days (positive = slower)"),
                ),
                (
                    "delta_percent",
                    models.FloatField(help_text="Percentage change from baseline"),
                ),
                (
                    "baseline_claim_count",
                    models.IntegerField(help_text="Claims in baseline window"),
                ),
                (
                    "current_claim_count",
                    models.IntegerField(help_text="Claims in current window"),
                ),
                (
                    "estimated_dollars_at_risk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cash impact from delayed payments",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score 0-1 based on sample size and data quality",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Human-readable signal summary"),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Signal-specific metrics and context"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Deterministic fingerprint of query criteria",
                        max_length=255,
                    ),
                ),
                (
                    "data_quality_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of data quality issues encountered",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_delay_signals",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "related_aggregates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="signals",
                        to="payrixa.paymentdelayaggregate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Delay Signal",
                "verbose_name_plural": "Payment Delay Signals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentDelayEvidenceArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payload_json",
                    models.JSONField(
                        default=dict, help_text="Structured evidence payload"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time to generate in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "claimset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_artifacts",
                        to="payrixa.paymentdelayclaimset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_delay_evidence",
                        to="payrixa.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_artifacts",
                        to="payrixa.paymentdelaysignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Delay Evidence Artifact",
                "verbose_name_plural": "Payment Delay Evidence Artifacts",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddField(
            model_name="paymentdelayclaimset",
            name="signal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claimsets",
                to="payrixa.paymentdelaysignal",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelayaggregate",
            index=models.Index(
                fields=["customer", "aggregate_date"],
                name="payrixa_pay_custome_db6e71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelayaggregate",
            index=models.Index(
                fields=["customer", "payer", "aggregate_date"],
                name="payrixa_pay_custome_c7f4a8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentdelayaggregate",
            constraint=models.UniqueConstraint(
                fields=("customer", "payer", "aggregate_date"),
                name="unique_payment_delay_aggregate",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelaysignal",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="payrixa_pay_custome_a14cb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelaysignal",
            index=models.Index(
                fields=["customer", "signal_type", "-created_at"],
                name="payrixa_pay_custome_30903a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelaysignal",
            index=models.Index(
                fields=["customer", "severity", "-created_at"],
                name="payrixa_pay_custome_7ee89d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelaysignal",
            index=models.Index(
                fields=["customer", "payer", "-created_at"],
                name="payrixa_pay_custome_7d7f42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelaysignal",
            index=models.Index(
                fields=["fingerprint"], name="payrixa_pay_fingerp_0ba184_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelayevidenceartifact",
            index=models.Index(
                fields=["customer", "-generated_at"],
                name="payrixa_pay_custome_bc9b0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelayevidenceartifact",
            index=models.Index(
                fields=["signal"], name="payrixa_pay_signal__47d185_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelayclaimset",
            index=models.Index(
                fields=["customer", "-frozen_at"], name="payrixa_pay_custome_74899c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdelayclaimset",
            index=models.Index(
                fields=["fingerprint"], name="payrixa_pay_fingerp_bf6e36_idx"
            ),
        ),
    ]
