# Generated by Django 5.2.10 on 2026-01-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrixa", "0017_paymentdelayaggregate_paymentdelayclaimset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertevent",
            name="payment_delay_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_events",
                to="payrixa.paymentdelaysignal",
            ),
        ),
    ]
