# Generated by Django 5.2.10 on 2026-02-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("upstream", "0029_imaging_pa_requirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe subscription ID (sub_xxxxx)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("essentials", "Essentials"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        default="essentials",
                        help_text="Subscription tier",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                        ],
                        db_index=True,
                        default="trialing",
                        help_text="Subscription status from Stripe",
                        max_length=30,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of current billing period",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="End of current billing period",
                        null=True,
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, help_text="Trial period end date", null=True
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Whether subscription will cancel at period end",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription was canceled",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer this subscription belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_subscription",
                "indexes": [
                    models.Index(
                        fields=["status", "current_period_end"],
                        name="subscription_status_period_idx",
                    ),
                    models.Index(
                        fields=["tier", "status"], name="subscription_tier_status_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tier__in", ["essentials", "professional", "enterprise"])
                        ),
                        name="subscription_tier_valid",
                    )
                ],
            },
        ),
    ]
