# Generated by Django 5.2.10 on 2026-02-01 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("upstream", "0030_add_stripe_customer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        db_index=True,
                        help_text="Start of usage period (first day of month)",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        db_index=True,
                        help_text="End of usage period (last day of month)",
                    ),
                ),
                (
                    "claims_processed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of claims ingested/processed",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "claims_scored",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of claims scored by AI",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "api_calls",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of API calls made",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "storage_bytes",
                    models.BigIntegerField(
                        default=0,
                        help_text="Storage used in bytes",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this usage belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_usage_record",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["customer", "period_start"],
                        name="usage_customer_period_idx",
                    )
                ],
                "unique_together": {("customer", "period_start")},
            },
        ),
    ]
