# Google Cloud Build configuration for Upstream
# Uses Cloud Build automatic substitutions

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/upstream:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/upstream:latest'
      - '.'

  # Step 2: Push Docker image with build ID tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/upstream:$BUILD_ID'

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/upstream:latest'

  # Step 4: Migration safety checks
  - name: 'gcr.io/$PROJECT_ID/upstream:$BUILD_ID'
    entrypoint: 'python'
    args:
      - 'manage.py'
      - 'makemigrations'
      - '--check'
      - '--dry-run'
      - '--noinput'
    env:
      - 'DJANGO_SETTINGS_MODULE=upstream.settings.prod'
    secretEnv:
      - 'SECRET_KEY'
      - 'DATABASE_URL'

  - name: 'gcr.io/$PROJECT_ID/upstream:$BUILD_ID'
    entrypoint: 'python'
    args:
      - 'manage.py'
      - 'migrate'
      - '--plan'
    env:
      - 'DJANGO_SETTINGS_MODULE=upstream.settings.prod'
    secretEnv:
      - 'SECRET_KEY'
      - 'DATABASE_URL'

  - name: 'gcr.io/$PROJECT_ID/upstream:$BUILD_ID'
    entrypoint: 'python'
    args:
      - 'manage.py'
      - 'check'
      - '--deploy'
    env:
      - 'DJANGO_SETTINGS_MODULE=upstream.settings.prod'
    secretEnv:
      - 'SECRET_KEY'

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'upstream-staging'
      - '--image'
      - 'gcr.io/$PROJECT_ID/upstream:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DJANGO_SETTINGS_MODULE=upstream.settings.prod'
      - '--set-secrets'
      - 'SECRET_KEY=django-secret-key:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest'

timeout: 1800s

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/django-secret-key/versions/latest
      env: 'SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: 'DATABASE_URL'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
