# Generated by Django 5.2.10 on 2026-02-01 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("upstream", "0030_add_stripe_customer_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the feature flag (snake_case)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of what this flag controls",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch - if False, flag is off for everyone",
                    ),
                ),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage of users to enable for (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "enabled_in_development",
                    models.BooleanField(
                        default=True, help_text="Enable in development environment"
                    ),
                ),
                (
                    "enabled_in_staging",
                    models.BooleanField(
                        default=True, help_text="Enable in staging environment"
                    ),
                ),
                (
                    "enabled_in_production",
                    models.BooleanField(
                        default=False, help_text="Enable in production environment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_flag_name", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("override_added", "Override Added"),
                            ("override_removed", "Override Removed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict, help_text="JSON object describing what changed"
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag Audit Log",
                "verbose_name_plural": "Feature Flag Audit Logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_value",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for this override (for audit purposes)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flag_overrides",
                        to="upstream.customer",
                    ),
                ),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="feature_flags.featureflag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flag_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag Override",
                "verbose_name_plural": "Feature Flag Overrides",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("customer__isnull", False)),
                        fields=("feature_flag", "customer"),
                        name="unique_flag_customer",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("feature_flag", "user"),
                        name="unique_flag_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("customer__isnull", False), ("user__isnull", True)
                            ),
                            models.Q(
                                ("customer__isnull", True), ("user__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="customer_or_user_not_both",
                    ),
                ],
            },
        ),
    ]
