# Generated by Django 5.2.10 on 2026-02-01 01:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("upstream", "0026_agentrun_codequalitymetric_databasequeryanalysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_confidence",
                    models.FloatField(
                        db_index=True,
                        help_text="Overall confidence score for automation decision",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "coding_confidence",
                    models.FloatField(
                        help_text="Confidence in CPT code accuracy",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "eligibility_confidence",
                    models.FloatField(
                        help_text="Confidence patient is eligible for service",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "medical_necessity_confidence",
                    models.FloatField(
                        help_text="Confidence medical necessity criteria are met",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "documentation_completeness",
                    models.FloatField(
                        help_text="Completeness of supporting documentation",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "denial_risk_score",
                    models.FloatField(
                        db_index=True,
                        help_text="Probability of denial based on historical patterns",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "fraud_risk_score",
                    models.FloatField(
                        help_text=(
                            "Fraud detection score (NPI patterns, billing anomalies)"
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "compliance_risk_score",
                    models.FloatField(
                        help_text="Risk of compliance violation (Stark, Anti-Kickback)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        help_text=(
                            "ML model version used for scoring (e.g., 'rf_v2.1')"
                        ),
                        max_length=50,
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        default=dict,
                        help_text=(
                            "Top features influencing score: "
                            "{'payer_history': 0.35, ...}"
                        ),
                    ),
                ),
                (
                    "prediction_reasoning",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Human-readable explanation of score (for transparency)"
                        ),
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("auto_execute", "Auto Execute"),
                            ("queue_review", "Queue for Review"),
                            ("escalate", "Escalate to Human"),
                            ("block", "Block - Compliance Red Line"),
                        ],
                        db_index=True,
                        help_text="Automation tier recommendation based on scoring",
                        max_length=50,
                    ),
                ),
                (
                    "automation_tier",
                    models.IntegerField(
                        choices=[
                            (1, "Tier 1: Auto Execute"),
                            (2, "Tier 2: Queue Review"),
                            (3, "Tier 3: Escalate"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "requires_human_review",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Legal/compliance requirement for human review",
                    ),
                ),
                (
                    "red_line_reason",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Why human review is required "
                            "(e.g., 'Medical necessity determination - CA SB 1120')"
                        ),
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="upstream.claimrecord",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_scores",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_claim_score",
            },
        ),
        migrations.CreateModel(
            name="CustomerAutomationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "automation_stage",
                    models.CharField(
                        choices=[
                            ("observe", "Stage 1: Observe (AI recommends, human acts)"),
                            (
                                "suggest",
                                "Stage 2: Suggest (AI pre-fills, human confirms)",
                            ),
                            (
                                "act_notify",
                                "Stage 3: Act + Notify (AI executes, human notified)",
                            ),
                            (
                                "full_autonomy",
                                "Stage 4: Full Autonomy (AI executes silently)",
                            ),
                        ],
                        default="observe",
                        help_text="Current trust calibration stage",
                        max_length=20,
                    ),
                ),
                (
                    "stage_start_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="When customer entered current stage",
                    ),
                ),
                (
                    "auto_execute_confidence",
                    models.FloatField(
                        default=0.95,
                        help_text="Minimum confidence score for autonomous execution",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "auto_execute_max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        help_text="Maximum dollar amount for autonomous submission",
                        max_digits=12,
                    ),
                ),
                (
                    "queue_review_min_confidence",
                    models.FloatField(
                        default=0.7,
                        help_text=(
                            "Minimum confidence for queueing "
                            "(below triggers escalation)"
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "queue_review_max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text=(
                            "Maximum dollar amount for review queue "
                            "(above triggers escalation)"
                        ),
                        max_digits=12,
                    ),
                ),
                (
                    "escalate_min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000,
                        help_text="Minimum dollar amount requiring escalation",
                        max_digits=12,
                    ),
                ),
                (
                    "auto_submit_claims",
                    models.BooleanField(
                        default=False,
                        help_text="Enable autonomous claim submission to payers",
                    ),
                ),
                (
                    "auto_check_status",
                    models.BooleanField(
                        default=True, help_text="Enable autonomous claim status checks"
                    ),
                ),
                (
                    "auto_verify_eligibility",
                    models.BooleanField(
                        default=True,
                        help_text="Enable autonomous patient eligibility verification",
                    ),
                ),
                (
                    "auto_submit_prior_auth",
                    models.BooleanField(
                        default=False,
                        help_text="Enable autonomous prior authorization submission",
                    ),
                ),
                (
                    "auto_modify_codes",
                    models.BooleanField(
                        default=False,
                        help_text="Enable autonomous CPT code corrections",
                    ),
                ),
                (
                    "auto_submit_appeals",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Enable autonomous appeal submission "
                            "(ALWAYS FALSE - legal requirement)"
                        ),
                    ),
                ),
                (
                    "shadow_mode_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Run AI in parallel with humans to validate accuracy",
                    ),
                ),
                (
                    "shadow_mode_start_date",
                    models.DateField(
                        blank=True, help_text="When shadow mode was enabled", null=True
                    ),
                ),
                (
                    "shadow_accuracy_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Current shadow mode accuracy (human agreement rate)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "shadow_mode_min_accuracy",
                    models.FloatField(
                        default=0.95,
                        help_text="Required accuracy before enabling live automation",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "notify_on_auto_execute",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Send notification after autonomous actions (Stage 3+)"
                        ),
                    ),
                ),
                (
                    "notify_on_escalation",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification when action escalated to human",
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for automation notifications",
                        max_length=254,
                    ),
                ),
                (
                    "undo_window_hours",
                    models.IntegerField(
                        default=2,
                        help_text="Hours available to undo autonomous actions",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "audit_all_actions",
                    models.BooleanField(
                        default=True,
                        help_text="Log all automation actions (HIPAA requirement)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_officer",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who controls automation guardrails",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_profile",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_customer_automation_profile",
            },
        ),
        migrations.CreateModel(
            name="ShadowModeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_recommended_action", models.CharField(max_length=50)),
                ("ai_confidence", models.FloatField()),
                ("human_action_taken", models.CharField(max_length=50)),
                ("human_decision_timestamp", models.DateTimeField()),
                (
                    "actions_match",
                    models.BooleanField(
                        help_text="Did AI recommendation match human decision?"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("true_positive", "True Positive: AI correct"),
                            ("true_negative", "True Negative: AI correct"),
                            ("false_positive", "False Positive: AI wrong"),
                            ("false_negative", "False Negative: AI wrong"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "discrepancy_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why human disagreed with AI (if applicable)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_results",
                        to="automation.claimscore",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_results",
                        to="upstream.customer",
                    ),
                ),
                (
                    "human_decision_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shadow_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upstream_shadow_mode_result",
            },
        ),
        migrations.AddIndex(
            model_name="claimscore",
            index=models.Index(
                fields=["customer", "overall_confidence"],
                name="claim_score_confidence_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimscore",
            index=models.Index(
                fields=["customer", "automation_tier"], name="claim_score_tier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimscore",
            index=models.Index(
                fields=["requires_human_review", "created_at"],
                name="claim_score_review_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shadowmoderesult",
            index=models.Index(
                fields=["customer", "actions_match", "created_at"],
                name="shadow_accuracy_idx",
            ),
        ),
    ]
