# Generated by Django 5.2.10 on 2026-01-24 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["customer", "alert_rule", "status"],
                name="alertevt_rule_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "payer", "cpt_group"], name="claim_drift_detect_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "submitted_date", "decided_date"],
                name="claim_lag_analysis_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "report_run", "-severity"],
                name="drift_report_sev_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["payer", "cpt_group", "-created_at"],
                name="drift_hist_trend_idx",
            ),
        ),
    ]
