# Generated by Django 5.2.10 on 2026-01-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0006_claimrecord_claim_source_hash_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimrecord",
            name="decided_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="claimrecord",
            name="payment_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Actual payment date (if different from decided_date)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="claimrecord",
            name="submitted_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="date_max",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="date_min",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="upload",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
