# Generated by Django 5.2.10 on 2026-01-26 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0016_alertrule_idx_alertrule_customer_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["customer", "enabled", "channel_type"],
                name="idx_notificationchannel_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="idx_webhookdelivery_retry"
            ),
        ),
    ]
