# Generated by Django 5.2.10 on 2026-01-26 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "upstream",
            "0017_notificationchannel_idx_notificationchannel_lookup_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(
                fields=["connection", "-start_time"], name="idx_integrationlog_history"
            ),
        ),
    ]
