# Generated by Django 5.2.10 on 2026-01-27 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0018_integrationlog_idx_integrationlog_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "-decided_date", "outcome"],
                name="claim_cust_date_outcome_cov",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["customer", "-created_at", "severity"],
                name="drift_cust_date_sev_cov",
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["customer", "-uploaded_at", "status"],
                name="upload_cust_date_status_cov",
            ),
        ),
    ]
