# Generated by Django 5.2.10 on 2026-01-27 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0019_add_covering_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="denialcascade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__gte", 0.0), ("confidence_score__lte", 1.0)
                ),
                name="denialcascade_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="denialcluster",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cluster_confidence__gte", 0.0), ("cluster_confidence__lte", 1.0)
                ),
                name="denialcluster_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentdelaysignal",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="paymentdelaysignal_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="predenialwarning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("denial_probability__gte", 0.0), ("denial_probability__lte", 1.0)
                ),
                name="predenialwarning_probability_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="predenialwarning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__gte", 0.0), ("confidence_score__lte", 1.0)
                ),
                name="predenialwarning_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="upload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["processing", "success", "failed", "partial"])
                ),
                name="upload_status_valid",
            ),
        ),
    ]
