# Generated by Django 5.2.10 on 2026-01-27 16:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0020_add_check_constraints_data_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payer", models.CharField(db_index=True, max_length=255)),
                ("cpt", models.CharField(db_index=True, max_length=20)),
                (
                    "denial_rate",
                    models.FloatField(
                        help_text="Historical denial rate: denied / total claims",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        help_text="Number of claims in baseline calculation",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Statistical confidence: min(sample_size / 100, 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_baselines",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_risk_baseline",
                "indexes": [
                    models.Index(
                        fields=["customer", "payer", "cpt"],
                        name="risk_baseline_lookup_idx",
                    ),
                    models.Index(
                        fields=["last_updated"], name="risk_baseline_updated_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("customer", "payer", "cpt"), name="unique_risk_baseline"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence_score__gte", 0.0),
                            ("confidence_score__lte", 1.0),
                        ),
                        name="risk_baseline_confidence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("denial_rate__gte", 0.0), ("denial_rate__lte", 1.0)
                        ),
                        name="risk_baseline_denial_rate_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sample_size__gte", 1)),
                        name="risk_baseline_sample_size_positive",
                    ),
                ],
            },
        ),
    ]
