# Generated by Django 5.2.10 on 2026-01-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0021_add_risk_baseline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("reauth", "Reauthorization Request"),
                            ("appeal", "Appeal Generation"),
                            ("high_risk_hold", "High Risk Hold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        help_text="Conditions that trigger this rule (payer, cpt_code, denial_rate_threshold, etc.)"
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        help_text="Actions to execute when triggered (action_type, payer_portal_steps, etc.)"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_automation_rule",
                "indexes": [
                    models.Index(
                        fields=["customer", "rule_type", "is_active"],
                        name="automation_rule_lookup_idx",
                    ),
                    models.Index(
                        fields=["is_active", "rule_type"],
                        name="automation_rule_active_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rule_type__in", ["reauth", "appeal", "high_risk_hold"])
                        ),
                        name="automation_rule_type_valid",
                    )
                ],
            },
        ),
    ]
