# Generated by Django 5.2.10 on 2026-01-27 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0022_add_automation_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimrecord",
            name="submitted_via",
            field=models.CharField(
                choices=[
                    ("csv_upload", "CSV Upload"),
                    ("ehr_webhook", "EHR Webhook"),
                    ("api", "API"),
                    ("batch_import", "Batch Import"),
                ],
                db_index=True,
                default="csv_upload",
                help_text="Source of claim submission for multi-channel ingestion tracking",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_number",
                    models.CharField(
                        help_text="Unique authorization number from payer",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "patient_identifier",
                    models.CharField(
                        help_text="Patient ID (should be encrypted in production)",
                        max_length=255,
                    ),
                ),
                ("payer", models.CharField(db_index=True, max_length=255)),
                (
                    "service_type",
                    models.CharField(
                        help_text="e.g., ABA Therapy, Physical Therapy", max_length=100
                    ),
                ),
                (
                    "cpt_codes",
                    models.JSONField(
                        help_text="List of authorized CPT codes: ['97151', '97153']"
                    ),
                ),
                ("auth_start_date", models.DateField()),
                ("auth_expiration_date", models.DateField(db_index=True)),
                (
                    "units_authorized",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "units_used",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRING_SOON", "Expiring Soon"),
                            ("EXPIRED", "Expired"),
                            ("RENEWED", "Renewed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "reauth_lead_time_days",
                    models.IntegerField(
                        default=21,
                        help_text="Days before expiration to trigger reauth (default 21 for 30-day window)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "auto_reauth_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable autonomous reauthorization submission without manual approval",
                    ),
                ),
                ("last_alert_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorizations",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_authorization",
                "indexes": [
                    models.Index(
                        fields=["customer", "status", "auth_expiration_date"],
                        name="authorization_expiring_idx",
                    ),
                    models.Index(
                        fields=["customer", "payer", "status"],
                        name="authorization_payer_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("units_used__lte", models.F("units_authorized"))
                        ),
                        name="authorization_units_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_event",
                    models.JSONField(
                        help_text="Event data that triggered the action: {type, claim_id, ...}"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        help_text="Action executed: submit_reauth, generate_appeal, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("ESCALATED", "Escalated to Alert"),
                        ],
                        db_index=True,
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        help_text="Execution details: outcomes, error messages, response data"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        help_text="Execution duration in milliseconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="upstream.customer",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rule that triggered this execution (nullable for ad-hoc actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="upstream.automationrule",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_execution_log",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-executed_at"],
                        name="execution_log_customer_idx",
                    ),
                    models.Index(
                        fields=["rule", "result"], name="execution_log_rule_idx"
                    ),
                ],
            },
        ),
    ]
