# Generated by Django 5.2.10 on 2026-01-31 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0023_claimrecord_submitted_via_authorization_executionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorization",
            name="specialty_metadata",
            field=models.JSONField(
                default=dict,
                help_text="Vertical-specific fields. ABA: {'bcba_required': true, 'credential_expiration': '2025-06-30'}. Imaging: {'rbm_provider': 'eviCore', 'pa_required': true}. Home Health: {'f2f_completed': true, 'oasis_date': '2025-01-15'}. Dialysis: {'ma_plan_type': 'Advantage', 'esrd_pps_bundle': 'CA2F'}",
            ),
        ),
        migrations.AlterField(
            model_name="authorization",
            name="auto_reauth_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable autonomous reauthorization submission"
            ),
        ),
        migrations.AlterField(
            model_name="authorization",
            name="reauth_lead_time_days",
            field=models.IntegerField(
                default=21,
                help_text="Days before expiration to trigger reauth (default 21)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="authorization",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("ABA", "ABA Therapy"),
                    ("PT", "Physical Therapy"),
                    ("OT", "Occupational Therapy"),
                    ("IMAGING", "Diagnostic Imaging"),
                    ("HOME_HEALTH", "Home Health"),
                    ("DIALYSIS", "Dialysis Services"),
                ],
                db_index=True,
                help_text="Service vertical (ABA, PT, OT, IMAGING, HOME_HEALTH, DIALYSIS)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="actions",
            field=models.JSONField(
                help_text="Actions to execute when triggered (action_type, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="trigger_conditions",
            field=models.JSONField(
                help_text="Conditions that trigger this rule (payer, cpt_code, etc.)"
            ),
        ),
        migrations.AddIndex(
            model_name="authorization",
            index=models.Index(
                fields=["customer", "service_type", "status"],
                name="authorization_service_idx",
            ),
        ),
    ]
