# Generated by Django 5.2.10 on 2026-02-01 00:44

from django.conf import settings
from django.db import connection, migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


def get_index_operation(index_def):
    """
    Return appropriate index operation based on database backend.
    Uses AddIndexConcurrently for PostgreSQL (zero-downtime).
    Falls back to AddIndex for SQLite/other databases.
    """
    if connection.vendor == "postgresql":
        return AddIndexConcurrently(**index_def)
    else:
        return migrations.AddIndex(**index_def)


class Migration(migrations.Migration):
    # atomic = False required for PostgreSQL CONCURRENTLY
    # SQLite ignores this and runs in transaction
    atomic = False

    dependencies = [
        ("upstream", "0024_update_authorization_multi_vertical"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # AlertRule partial index for evaluation ordering
        migrations.RunPython(
            lambda apps, schema_editor: None,  # Forward no-op
            lambda apps, schema_editor: None,  # Reverse no-op
            elidable=True,
        ),
        # Placeholder replaced at runtime with correct operation
    ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Replace placeholder operations with database-specific ones
        self.operations = [
            get_index_operation(
                {
                    "model_name": "alertrule",
                    "index": models.Index(
                        condition=models.Q(("enabled", True)),
                        fields=["customer", "-routing_priority"],
                        name="alertrule_eval_priority_idx",
                    ),
                }
            ),
            get_index_operation(
                {
                    "model_name": "userprofile",
                    "index": models.Index(
                        fields=["customer", "role"],
                        name="userprofile_customer_role_idx",
                    ),
                }
            ),
        ]
