# Generated by Django 5.2.10 on 2026-02-01 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0025_add_missing_indexes_phase6"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("code_quality", "Code Quality Auditor"),
                            ("db_performance", "Database Performance Optimizer"),
                            ("test_coverage", "Test Coverage Analyzer"),
                            ("migration_safety", "Migration Safety Checker"),
                            ("hipaa_compliance", "HIPAA Compliance Monitor"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Execution"),
                            ("pre_commit", "Pre-Commit Hook"),
                            ("pre_deploy", "Pre-Deploy Check"),
                            ("scheduled", "Scheduled Run"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("findings_count", models.IntegerField(default=0)),
                ("critical_count", models.IntegerField(default=0)),
                ("high_count", models.IntegerField(default=0)),
                ("medium_count", models.IntegerField(default=0)),
                ("low_count", models.IntegerField(default=0)),
                ("git_commit", models.CharField(blank=True, max_length=40)),
                ("git_branch", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("report_path", models.CharField(blank=True, max_length=500)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upstream_agent_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeQualityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.FloatField()),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(default=True)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_metrics",
                        to="upstream.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_code_quality_metric",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseQueryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_pattern", models.TextField()),
                ("file_path", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("n_plus_one", "N+1 Query"),
                            ("missing_index", "Missing Index"),
                            ("unoptimized", "Unoptimized Query"),
                            ("cartesian_product", "Cartesian Product"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estimated_impact",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("suggestion", models.TextField()),
                ("example_optimized", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_analyses",
                        to="upstream.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_db_query_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("code_snippet", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("fixed", "Fixed"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="upstream.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_finding",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("migration_file", models.CharField(max_length=500)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("caution", "Caution"),
                            ("high_risk", "High Risk"),
                            ("destructive", "Destructive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operations", models.JSONField(default=list)),
                ("potential_issues", models.JSONField(default=list)),
                ("rollback_possible", models.BooleanField(default=True)),
                ("estimated_duration", models.CharField(blank=True, max_length=100)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_analyses",
                        to="upstream.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_migration_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCoverageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("total_lines", models.IntegerField()),
                ("covered_lines", models.IntegerField()),
                ("coverage_percentage", models.FloatField()),
                ("missing_lines", models.JSONField(default=list)),
                ("untested_functions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_reports",
                        to="upstream.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_test_coverage_report",
                "ordering": ["coverage_percentage"],
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["agent_type", "-started_at"],
                name="upstream_ag_agent_t_d543e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["status", "-started_at"], name="upstream_ag_status_4cf94e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codequalitymetric",
            index=models.Index(
                fields=["metric_name", "-created_at"],
                name="upstream_co_metric__8599e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["agent_run", "severity"], name="upstream_fi_agent_r_b38632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["status", "-created_at"], name="upstream_fi_status_c8a778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["category", "severity"], name="upstream_fi_categor_3b036a_idx"
            ),
        ),
    ]
