# Generated by Django 5.2.10 on 2026-02-01 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0026_agentrun_codequalitymetric_databasequeryanalysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialysisMABaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpt",
                    models.CharField(
                        db_index=True,
                        help_text="CPT procedure code for dialysis service",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "average_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average traditional Medicare payment for this CPT",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        help_text="Number of claims in baseline calculation",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Last time this baseline was updated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dialysis MA Baseline",
                "verbose_name_plural": "Dialysis MA Baselines",
                "db_table": "upstream_dialysis_ma_baseline",
                "indexes": [
                    models.Index(fields=["cpt"], name="dialysis_baseline_cpt_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("average_payment__gte", 0)),
                        name="dialysis_baseline_payment_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sample_size__gte", 1)),
                        name="dialysis_baseline_sample_positive",
                    ),
                ],
            },
        ),
    ]
