# Generated by Django 5.2.10 on 2026-02-01 05:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0026_agentrun_codequalitymetric_databasequeryanalysis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DialysisMABaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cpt",
                    models.CharField(
                        db_index=True,
                        help_text="CPT code for dialysis procedure",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "average_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average traditional Medicare payment amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        help_text="Number of claims used to calculate average",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        db_index=True,
                        help_text="Date when baseline was last updated from CMS data",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upstream_dialysismabaseline",
                "verbose_name": "Dialysis MA Baseline",
                "verbose_name_plural": "Dialysis MA Baselines",
                "ordering": ["cpt"],
                "indexes": [
                    models.Index(fields=["cpt"], name="dialysis_ma_baseline_cpt_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("average_payment__gte", 0)),
                        name="dialysis_ma_baseline_payment_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sample_size__gte", 1)),
                        name="dialysis_ma_baseline_sample_positive",
                    ),
                ],
            },
        ),
    ]
