# Generated by Django 5.2.10 on 2026-02-01 06:14

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0027_dialysis_ma_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ABAAuthorizationTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "units_authorized",
                    models.IntegerField(
                        help_text="Total units authorized for this period",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "units_used",
                    models.IntegerField(
                        default=0,
                        help_text="Units consumed so far",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weekly_usage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average weekly unit consumption rate",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "projected_exhaustion_date",
                    models.DateField(
                        blank=True,
                        help_text="Projected date when units will be exhausted",
                        null=True,
                    ),
                ),
                (
                    "last_usage_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="When units_used was last updated",
                        null=True,
                    ),
                ),
                (
                    "last_alert_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date an exhaustion alert was sent",
                        null=True,
                    ),
                ),
                (
                    "last_alert_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of last alert sent (e.g., '90_percent', 'exhausted')",
                        max_length=20,
                    ),
                ),
                (
                    "authorization",
                    models.OneToOneField(
                        help_text="Associated ABA authorization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aba_tracker",
                        to="upstream.authorization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ABA Authorization Tracker",
                "verbose_name_plural": "ABA Authorization Trackers",
                "db_table": "upstream_aba_authorization_tracker",
                "indexes": [
                    models.Index(
                        fields=["projected_exhaustion_date"],
                        name="aba_tracker_exhaust_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "units_used__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("units_authorized"), "*", models.Value(2)
                                ),
                            )
                        ),
                        name="aba_tracker_units_reasonable",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("units_authorized__gte", 1)),
                        name="aba_tracker_units_auth_positive",
                    ),
                ],
            },
        ),
    ]
