# Generated by Django 5.2.10 on 2026-02-01
# This migration removes DialysisMABaseline from upstream state.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0027_dialysis_ma_baseline"),
        ("dialysis", "0001_initial"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="DialysisMABaseline"),
            ],
            database_operations=[],
        ),
    ]
