# Generated by Django 5.2.10 on 2026-02-01 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0028_aba_authorization_tracker"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagingPARequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payer",
                    models.CharField(
                        db_index=True,
                        help_text="Payer name or ID requiring PA",
                        max_length=100,
                    ),
                ),
                (
                    "cpt",
                    models.CharField(
                        db_index=True,
                        help_text="CPT code for imaging procedure",
                        max_length=20,
                    ),
                ),
                (
                    "pa_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether PA is required for this payer/CPT",
                    ),
                ),
                (
                    "rbm_provider",
                    models.CharField(
                        choices=[
                            ("EVICORE", "eviCore"),
                            ("AIM", "AIM Specialty Health"),
                            ("CARECORE", "CareCore National"),
                            ("NIA", "National Imaging Associates"),
                            ("MAGELLAN", "Magellan Healthcare"),
                            ("OTHER", "Other"),
                            ("NONE", "Direct to Payer"),
                        ],
                        default="NONE",
                        help_text="RBM provider handling PA requests",
                        max_length=20,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date this PA requirement became effective",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this PA requirement ends (null = active)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about PA requirements",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging PA Requirement",
                "verbose_name_plural": "Imaging PA Requirements",
                "db_table": "upstream_imagingparequirement",
                "ordering": ["payer", "cpt"],
                "indexes": [
                    models.Index(
                        fields=["payer", "cpt"], name="imaging_pa_payer_cpt_idx"
                    ),
                    models.Index(
                        fields=["effective_date"], name="imaging_pa_effective_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payer", "cpt", "effective_date"),
                        name="imaging_pa_unique_payer_cpt_date",
                    )
                ],
            },
        ),
    ]
