# Generated by Django 5.2.10 on 2026-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0029_imaging_pa_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe customer ID (cus_xxxxx)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
