# Generated by Django 5.2.10 on 2026-02-01 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0031_add_behavioral_prediction_drift_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payer", models.CharField(db_index=True, max_length=255)),
                (
                    "drift_type",
                    models.CharField(
                        choices=[
                            ("DENIAL_RATE", "Denial Rate"),
                            ("DECISION_TIME", "Decision Time"),
                            ("PAYMENT_AMOUNT", "Payment Amount"),
                            ("APPROVAL_RATE", "Approval Rate"),
                            ("PROCESSING_DELAY", "Processing Delay"),
                            ("AUTH_FAILURE_RATE", "Authorization Failure Rate"),
                            ("BEHAVIORAL_PREDICTION", "Behavioral Prediction"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "affected_customer_count",
                    models.IntegerField(
                        help_text="Number of customers affected by this pattern",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(
                        help_text="Human-readable summary of the cross-customer pattern"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed pattern data: {customer_ids, avg_delta, date_range, etc.}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this network-wide issue was resolved",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "upstream_network_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payer", "drift_type"],
                        name="network_alert_payer_type_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="network_alert_sev_date_idx",
                    ),
                    models.Index(
                        fields=["drift_type", "-created_at"],
                        name="network_alert_type_date_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("affected_customer_count__gte", 1)),
                        name="network_alert_count_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("severity__in", ["LOW", "MEDIUM", "HIGH", "CRITICAL"])
                        ),
                        name="network_alert_severity_valid",
                    ),
                ],
            },
        ),
    ]
