# Generated by Django 5.2.10 on 2026-02-01 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0032_networkalert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeHealthPDGMGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("EARLY", "Early (within 30 days of discharge)"),
                            ("LATE", "Late (31+ days or community admission)"),
                        ],
                        db_index=True,
                        help_text="Admission source/timing category",
                        max_length=10,
                    ),
                ),
                (
                    "clinical_group",
                    models.CharField(
                        choices=[
                            ("MMTA", "Medication Management, Teaching and Assessment"),
                            ("MMTA_SURG", "MMTA - Surgical Aftercare"),
                            ("WOUND", "Wound/Ostomy Care"),
                            ("NEURO_REHAB", "Neurological/Stroke Rehabilitation"),
                            ("COMPLEX_NURS", "Complex Nursing Interventions"),
                            ("MS_REHAB", "Musculoskeletal Rehabilitation"),
                            ("BEHAVIORAL", "Behavioral Health Care"),
                            ("CARDIAC", "Cardiac/Circulatory Care"),
                            ("DIABETES", "Endocrine/Diabetes Care"),
                            ("RESP", "Respiratory Care"),
                            ("GI_GU", "GI/GU Care"),
                            ("SKIN", "Skin Care (non-wound)"),
                        ],
                        db_index=True,
                        help_text="Clinical grouping based on principal diagnosis",
                        max_length=20,
                    ),
                ),
                (
                    "functional_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low functional impairment"),
                            ("MEDIUM", "Medium functional impairment"),
                            ("HIGH", "High functional impairment"),
                        ],
                        db_index=True,
                        help_text="Functional level based on OASIS scores",
                        max_length=10,
                    ),
                ),
                (
                    "comorbidity",
                    models.CharField(
                        choices=[
                            ("NONE", "No qualifying comorbidities"),
                            ("LOW", "Low comorbidity adjustment"),
                            ("HIGH", "High comorbidity adjustment"),
                        ],
                        db_index=True,
                        help_text="Comorbidity adjustment level",
                        max_length=10,
                    ),
                ),
                (
                    "hipps_code",
                    models.CharField(
                        help_text="HIPPS code for this PDGM group",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "payment_weight",
                    models.FloatField(
                        help_text="Payment weight multiplier for this group",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Health PDGM Group",
                "verbose_name_plural": "Home Health PDGM Groups",
                "db_table": "upstream_homehealthpdgmgroup",
                "ordering": [
                    "timing",
                    "clinical_group",
                    "functional_level",
                    "comorbidity",
                ],
            },
        ),
        migrations.CreateModel(
            name="HomeHealthEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient_identifier",
                    models.CharField(
                        help_text="Patient ID (should be encrypted in production)",
                        max_length=255,
                    ),
                ),
                (
                    "payer",
                    models.CharField(
                        db_index=True,
                        help_text="Primary payer for this episode",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Episode"),
                            ("COMPLETED", "Episode Completed"),
                            ("DISCHARGED", "Patient Discharged"),
                            ("TRANSFERRED", "Transferred to Another Agency"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "soc_date",
                    models.DateField(db_index=True, help_text="Start of Care date"),
                ),
                (
                    "episode_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Episode end date (60-day periods)",
                        null=True,
                    ),
                ),
                (
                    "f2f_date",
                    models.DateField(
                        blank=True, help_text="Face-to-Face encounter date", null=True
                    ),
                ),
                (
                    "f2f_physician",
                    models.CharField(
                        blank=True,
                        help_text="Certifying physician for F2F",
                        max_length=255,
                    ),
                ),
                (
                    "f2f_is_valid",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether F2F timing is within requirements",
                    ),
                ),
                (
                    "noa_submitted_date",
                    models.DateField(
                        blank=True,
                        help_text="Date NOA was submitted to Medicare",
                        null=True,
                    ),
                ),
                (
                    "noa_deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="NOA submission deadline (SOC + 5 days)",
                        null=True,
                    ),
                ),
                (
                    "noa_is_timely",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether NOA was submitted on time",
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        blank=True,
                        help_text="EARLY or LATE timing classification",
                        max_length=10,
                    ),
                ),
                (
                    "clinical_group",
                    models.CharField(
                        blank=True,
                        help_text="Clinical group classification",
                        max_length=20,
                    ),
                ),
                (
                    "functional_level",
                    models.CharField(
                        blank=True,
                        help_text="Functional impairment level",
                        max_length=10,
                    ),
                ),
                (
                    "comorbidity",
                    models.CharField(
                        blank=True,
                        help_text="Comorbidity adjustment level",
                        max_length=10,
                    ),
                ),
                (
                    "oasis_date",
                    models.DateField(
                        blank=True, help_text="Date of OASIS assessment", null=True
                    ),
                ),
                (
                    "oasis_functional_score",
                    models.IntegerField(
                        blank=True,
                        help_text="OASIS functional score (0-30)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homehealth_episodes",
                        to="upstream.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pdgm_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned PDGM group for this episode",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episodes",
                        to="upstream.homehealthpdgmgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Health Episode",
                "verbose_name_plural": "Home Health Episodes",
                "db_table": "upstream_homehealthepisode",
                "ordering": ["-soc_date"],
            },
        ),
        migrations.AddIndex(
            model_name="homehealthpdgmgroup",
            index=models.Index(
                fields=["timing", "clinical_group"], name="hh_pdgm_timing_grp_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="homehealthpdgmgroup",
            constraint=models.UniqueConstraint(
                fields=("timing", "clinical_group", "functional_level", "comorbidity"),
                name="hh_pdgm_unique_combo",
            ),
        ),
        migrations.AddConstraint(
            model_name="homehealthpdgmgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("payment_weight__gte", 0)),
                name="hh_pdgm_weight_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="homehealthepisode",
            index=models.Index(
                fields=["customer", "status", "soc_date"], name="hh_ep_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homehealthepisode",
            index=models.Index(
                fields=["customer", "payer", "-soc_date"], name="hh_ep_payer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homehealthepisode",
            index=models.Index(
                fields=["customer", "f2f_is_valid"], name="hh_ep_f2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homehealthepisode",
            index=models.Index(
                fields=["customer", "noa_is_timely"], name="hh_ep_noa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="homehealthepisode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("oasis_functional_score__gte", 0),
                        ("oasis_functional_score__lte", 30),
                    ),
                    ("oasis_functional_score__isnull", True),
                    _connector="OR",
                ),
                name="hh_ep_oasis_range",
            ),
        ),
    ]
