# Generated by Django on 2026-02-01
# Specialty Module System - Customer specialty tracking and alert filtering

from django.db import migrations, models
import django.db.models.deletion


def backfill_alert_specialties(apps, schema_editor):
    """
    Backfill existing alerts with specialty based on payload['type'].
    Uses prefix matching to categorize alerts by specialty.
    """
    AlertEvent = apps.get_model("upstream", "AlertEvent")

    TYPE_TO_SPECIALTY = {
        # Dialysis
        "dialysis_ma_variance": "DIALYSIS",
        "dialysis_ma_payment_variance": "DIALYSIS",
        "dialysis_esrd_pps": "DIALYSIS",
        "dialysis_payment_spike": "DIALYSIS",
        # ABA
        "aba_utilization": "ABA",
        "aba_unit_exhaustion": "ABA",
        "aba_authorization_expiring": "ABA",
        "aba_reauth_expiration": "ABA",
        "aba_credential_expiration": "ABA",
        # Imaging
        "imaging_missing_pa": "IMAGING",
        "imaging_documentation": "IMAGING",
        "imaging_incomplete_documentation": "IMAGING",
        "imaging_rbm_pa_required": "IMAGING",
        # Home Health
        "homehealth_pdgm_mismatch": "HOME_HEALTH",
        "homehealth_f2f_timing": "HOME_HEALTH",
        "homehealth_noa_deadline": "HOME_HEALTH",
        "homehealth_recertification_due": "HOME_HEALTH",
        # PT/OT
        "ptot_8_minute_violation": "PTOT",
        "ptot_unit_overbilling": "PTOT",
        "ptot_missing_kx_modifier": "PTOT",
        "ptot_gcode_missing": "PTOT",
    }

    # Batch update for efficiency
    for alert_type, specialty in TYPE_TO_SPECIALTY.items():
        # Update alerts where payload contains this type
        AlertEvent.objects.filter(specialty="CORE", payload__type=alert_type).update(
            specialty=specialty
        )

    # Fallback: prefix matching for any missed alerts
    prefix_mapping = [
        ("dialysis_", "DIALYSIS"),
        ("aba_", "ABA"),
        ("imaging_", "IMAGING"),
        ("homehealth_", "HOME_HEALTH"),
        ("ptot_", "PTOT"),
    ]

    for prefix, specialty in prefix_mapping:
        AlertEvent.objects.filter(
            specialty="CORE", payload__type__startswith=prefix
        ).update(specialty=specialty)


def reverse_backfill(apps, schema_editor):
    """Reverse backfill - set all alerts back to CORE."""
    AlertEvent = apps.get_model("upstream", "AlertEvent")
    AlertEvent.objects.all().update(specialty="CORE")


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0035_add_ptot_gcode_models"),
    ]

    operations = [
        # 1. Add specialty_type to Customer model
        migrations.AddField(
            model_name="customer",
            name="specialty_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIALYSIS", "Dialysis"),
                    ("ABA", "ABA Therapy"),
                    ("PTOT", "PT/OT"),
                    ("IMAGING", "Imaging"),
                    ("HOME_HEALTH", "Home Health"),
                ],
                db_index=True,
                help_text="Customer's primary specialty (selected during onboarding)",
                max_length=20,
                null=True,
            ),
        ),
        # 2. Create CustomerSpecialtyModule junction table
        migrations.CreateModel(
            name="CustomerSpecialtyModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("DIALYSIS", "Dialysis"),
                            ("ABA", "ABA Therapy"),
                            ("PTOT", "PT/OT"),
                            ("IMAGING", "Imaging"),
                            ("HOME_HEALTH", "Home Health"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this module is currently enabled",
                    ),
                ),
                (
                    "enabled_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this module was first enabled",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the customer's primary specialty",
                    ),
                ),
                (
                    "stripe_subscription_item_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe subscription item for add-on billing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialty_modules",
                        to="upstream.customer",
                    ),
                ),
            ],
            options={
                "db_table": "upstream_customer_specialty_module",
                "unique_together": {("customer", "specialty")},
            },
        ),
        # 3. Add indexes to CustomerSpecialtyModule
        migrations.AddIndex(
            model_name="customerspecialtymodule",
            index=models.Index(
                fields=["customer", "specialty"],
                name="csm_customer_specialty_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerspecialtymodule",
            index=models.Index(
                fields=["customer", "enabled"],
                name="csm_customer_enabled_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerspecialtymodule",
            index=models.Index(
                fields=["customer", "is_primary"],
                name="csm_customer_primary_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerspecialtymodule",
            index=models.Index(
                fields=["customer", "specialty", "enabled"],
                name="csm_customer_spec_enabled_idx",
            ),
        ),
        # 4. Add specialty field to AlertEvent
        migrations.AddField(
            model_name="alertevent",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("DIALYSIS", "Dialysis"),
                    ("ABA", "ABA Therapy"),
                    ("PTOT", "PT/OT"),
                    ("IMAGING", "Imaging"),
                    ("HOME_HEALTH", "Home Health"),
                    ("CORE", "Core Platform"),
                ],
                db_index=True,
                default="CORE",
                help_text="Specialty module this alert belongs to",
                max_length=20,
            ),
        ),
        # 5. Add indexes for AlertEvent specialty filtering
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["customer", "specialty", "-triggered_at"],
                name="alertevt_specialty_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["customer", "specialty", "status"],
                name="alertevt_spec_status_idx",
            ),
        ),
        # 6. Backfill existing alerts with specialty
        migrations.RunPython(
            backfill_alert_specialties,
            reverse_code=reverse_backfill,
        ),
    ]
