# Generated by Django 5.2.10 on 2026-02-01 05:38

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0036_customer_specialty_modules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EHRConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ehr_type",
                    models.CharField(
                        choices=[
                            ("epic", "Epic FHIR R4"),
                            ("cerner", "Cerner/Oracle Health"),
                            ("athena", "athenahealth"),
                        ],
                        db_index=True,
                        help_text="EHR vendor type",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this connection (e.g., 'Main Hospital Epic')",
                        max_length=100,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(help_text="OAuth 2.0 client ID", max_length=255),
                ),
                (
                    "client_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="OAuth 2.0 client secret (encrypted at rest)"
                    ),
                ),
                (
                    "oauth_endpoint",
                    models.URLField(help_text="OAuth 2.0 token endpoint URL"),
                ),
                ("fhir_endpoint", models.URLField(help_text="FHIR API base URL")),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this connection is active",
                    ),
                ),
                (
                    "last_poll",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful poll timestamp",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error message if connection failed",
                        null=True,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        help_text="Current connection health status",
                        max_length=20,
                    ),
                ),
                (
                    "health_checked_at",
                    models.DateTimeField(
                        blank=True, help_text="Last health check timestamp", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ehr_connections",
                        to="upstream.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EHR Connection",
                "verbose_name_plural": "EHR Connections",
            },
        ),
        migrations.CreateModel(
            name="EHRSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "records_fetched",
                    models.IntegerField(
                        default=0, help_text="Number of records fetched from EHR"
                    ),
                ),
                (
                    "records_created",
                    models.IntegerField(
                        default=0, help_text="Number of ClaimRecords created"
                    ),
                ),
                (
                    "records_updated",
                    models.IntegerField(
                        default=0, help_text="Number of ClaimRecords updated"
                    ),
                ),
                (
                    "records_skipped",
                    models.IntegerField(
                        default=0, help_text="Number of records skipped (duplicates)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if sync failed", null=True
                    ),
                ),
                (
                    "sync_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional sync metadata (pagination info, etc.)",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="upstream.ehrconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EHR Sync Log",
                "verbose_name_plural": "EHR Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ehrconnection",
            index=models.Index(
                fields=["customer", "ehr_type", "enabled"],
                name="idx_ehrconnection_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="ehrconnection",
            index=models.Index(
                fields=["enabled", "ehr_type"], name="idx_ehrconnection_polling"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ehrconnection",
            unique_together={("customer", "name")},
        ),
        migrations.AddIndex(
            model_name="ehrsynclog",
            index=models.Index(
                fields=["connection", "-started_at"], name="idx_ehrsynclog_history"
            ),
        ),
        migrations.AddIndex(
            model_name="ehrsynclog",
            index=models.Index(
                fields=["status", "-started_at"], name="idx_ehrsynclog_status"
            ),
        ),
        migrations.AddIndex(
            model_name="ehrsynclog",
            index=models.Index(fields=["-started_at"], name="idx_ehrsynclog_retention"),
        ),
    ]
