# Generated by Django 5.2.10 on 2026-02-02 21:34

from django.db import migrations


class Migration(migrations.Migration):
    """
    Merge migration that consolidates multiple migration branches.

    Note: Both 0027_ehr_connection_models and 0037_ehr_connection_models
    contain EHR model creation. We depend on 0037 which includes all models
    and is the properly sequenced migration.
    """

    dependencies = [
        ("upstream", "0037_ehr_connection_models"),
    ]

    operations = []
