# Generated by Django 5.2.10 on 2026-02-02 21:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0038_merge_20260202_2134"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTimingTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payer", models.CharField(db_index=True, max_length=255)),
                (
                    "analysis_start_date",
                    models.DateField(help_text="Start of the 4-week analysis window"),
                ),
                (
                    "analysis_end_date",
                    models.DateField(help_text="End of the analysis window"),
                ),
                (
                    "weekly_metrics",
                    models.JSONField(
                        default=list,
                        help_text="Weekly payment timing data: [{week_start, week_end, avg_days, claim_count, total_billed}, ...]",
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("WORSENING", "Worsening"),
                            ("IMPROVING", "Improving"),
                            ("STABLE", "Stable"),
                        ],
                        db_index=True,
                        help_text="Overall trend direction across weeks",
                        max_length=20,
                    ),
                ),
                (
                    "consecutive_worsening_weeks",
                    models.IntegerField(
                        default=0,
                        help_text="Number of consecutive weeks with increasing payment days",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "baseline_avg_days",
                    models.FloatField(
                        help_text="Average days-to-payment in first week"
                    ),
                ),
                (
                    "current_avg_days",
                    models.FloatField(
                        help_text="Average days-to-payment in most recent week"
                    ),
                ),
                (
                    "total_delta_days",
                    models.FloatField(
                        help_text="Total change in days from first to last week"
                    ),
                ),
                (
                    "avg_weekly_change",
                    models.FloatField(help_text="Average days change per week"),
                ),
                (
                    "estimated_revenue_delay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated revenue delayed due to slower payments ($)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "total_billed_in_window",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total billed amount in the analysis window",
                        max_digits=14,
                    ),
                ),
                (
                    "total_claim_count",
                    models.IntegerField(
                        help_text="Total claims analyzed across all weeks"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score based on sample size and trend consistency",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Human-readable trend summary"),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Deterministic fingerprint for deduplication",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_timing_trends",
                        to="upstream.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Timing Trend",
                "verbose_name_plural": "Payment Timing Trends",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymenttimingtrend",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="upstream_pa_custome_3747dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttimingtrend",
            index=models.Index(
                fields=["customer", "payer", "-created_at"],
                name="upstream_pa_custome_aa74b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttimingtrend",
            index=models.Index(
                fields=["customer", "trend_direction", "-created_at"],
                name="upstream_pa_custome_95c817_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttimingtrend",
            index=models.Index(
                fields=["customer", "severity", "-created_at"],
                name="upstream_pa_custome_51bef4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttimingtrend",
            index=models.Index(
                fields=["fingerprint"], name="upstream_pa_fingerp_f30fbc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttimingtrend",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="paymenttimingtrend_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttimingtrend",
            constraint=models.CheckConstraint(
                condition=models.Q(("consecutive_worsening_weeks__gte", 0)),
                name="paymenttimingtrend_weeks_nonnegative",
            ),
        ),
    ]
